# need 4 gpus

project: coconut
save_path: models
name: prosqa-coconut

only_eval: True

coconut: True
cot: False
no_thoughts: False
no_cot: False

c_thought: 1
epochs_per_stage: 1
max_latent_stage: 6
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0
model_id: openai-community/gpt2
load_model_path: models/prosqa-coconut/checkpoint_1
seed: 0
resume: 40
bf16: False
train_path: data/prosqa_train.json
val_path: data/prosqa_test.json
reset_optimizer: True
batch_size_training: 8
debug: False
gradient_accumulation_steps: 2
num_epochs: 42
lr: !!float "1e-4"
weight_decay: 0.01